### ISSUE TITLE
Install libopus, libogg, libzstd

### ISSUE THREAD

**Issue by alphaonex86** [a12e/docker-qt#3]
Hi,
I don't found your email to contact you directly, mine: alpha_one_x86@first-world.info
I fail to compile libopus, libogg, libzstd under your container, I thinks due to my lack of knowledges.
Can you provide way to do that's?
Cheers,

**Comment by a12e** [comment]
What you ask seems to be outside of the scope of this Docker image. Sorry, but I don't provide free support for support.

You may want to learn about how to compile these three libraries under Android. If it turns out that there is an issue related to how the docker-qt image is built, feel free to open an issue. The docker-qt image is just an Ubuntu, with all Android and Qt tools unpacked at the right place, ready to compile.

Cheers
